# Tokyo Night theme for sway
#
# Colors
#
# background            #1a1b26
# foreground            #a9b1d6
# frame                 #414868
# urgent_background     #1a1b26
# urgent_foreground     #f7768e
# urgent_frame          #f7768e
# normal_background     #1a1b26
# normal_foreground     #c0caf5
# normal_frame          #7dcfff

# class                 border      background  text        indicator   child_border
client.focused          #7dcfff     #1a1b26     #c0caf5     #7dcfff     #7dcfff
client.unfocused        #414868     #1a1b26     #a9b1d6     #414868     #414868
client.focused_inactive #414868     #1a1b26     #a9b1d6     #414868     #414868
client.urgent           #f7768e     #1a1b26     #f7768e     #f7768e     #f7768e
client.placeholder      #000000     #000000     #ffffff     #000000     #000000

client.background       #1a1b26
